Repository Android-3rd-team-3/Y-Media-App, pull requests merged in 2024-05, with the labels that each got.

#1 homeFragment to develop
  .idea/gradle.xml
  app/src/main/java/com/example/ymediaapp/presentation/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/model/YoutubeSearchViewModel.kt
  app/src/main/res/drawable/bg_rv_item_image.xml
  app/src/main/res/drawable/ic_popup.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/rv_item_home.xml
  app/src/main/res/menu/popup_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: add

#3 homeFragment to develop
  app/src/main/java/com/example/ymediaapp/presentation/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/SearchRepository.kt
Labels: add

#4 네트워크 API 작업 후 병합
  app/src/main/java/com/example/ymediaapp/data/remote/YoutubeResponse.kt
  app/src/main/java/com/example/ymediaapp/data/remote/api/YoutubeService.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/ChannelResponse.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/ThumbnailsResponse.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/VideoCategoryResponse.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/VideoResponse.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/YoutubeListResponse.kt
  app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/network/AuthorizationInterceptor.kt
  app/src/main/java/com/example/ymediaapp/network/RetrofitClient.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/DummyAuth.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoRvAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
  app/src/main/res/drawable/dummy_background.jpg
  app/src/main/res/drawable/dummy_profile.jpg
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/item_my_video_favorite.xml
Labels: add

#5 pr 관련 수정, room 코드 작성
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomDatabase.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/main/MainActivity.kt
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/my_video.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: add

#6 homeFragment to develop
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeChannelAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/mapper/YoutubeSearchMapper.kt
Labels: fix

#8 Revert "pr 관련 수정, room 코드 작성"
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomDatabase.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/main/MainActivity.kt
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/my_video.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: rollback

#9 home fragment to develop
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeChannelAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/mapper/YoutubeSearchMapper.kt
Labels: add, fix

#10 Room 코드 작성, pr 피드백 반영
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomDatabase.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/main/MainActivity.kt
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/my_video.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: fix

#12 videoRepository 추가
  app/src/main/java/com/example/ymediaapp/data/database/RoomDatabase.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/data/repository/VideoRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/VideoRepository.kt
Labels: add

#11 homeFragment to develop
  app/src/main/java/com/example/ymediaapp/presentation/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeSpinnerAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/model/YoutubeSearchViewModel.kt
  app/src/main/res/drawable/bg_spinner.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/rv_item_home.xml
  app/src/main/res/layout/spinner_item_dropdown_home.xml
  app/src/main/res/layout/spinner_item_home.xml
  app/src/main/res/menu/popup_menu.xml
  app/src/main/res/values/styles.xml
Labels: add, fix, del, style

#14 MyVideo 화면에서 ViewModel 사용하게 로직 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoRvAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
  app/src/main/res/layout/fragment_my_video.xml
Labels: update

#15 API 수정
  app/src/main/java/com/example/ymediaapp/data/remote/api/YoutubeService.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/SearchResponse.kt
Labels: fix

#13 searchFragment 금일까지 작업한 사항 입니다.
  app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/presentation/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/SearchRepository.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchViewModel.kt
  app/src/main/res/color/chip_box_color.xml
  app/src/main/res/color/chip_box_text.xml
  app/src/main/res/drawable/ic_search_btn.png
  app/src/main/res/drawable/sampleimg.png
  app/src/main/res/drawable/search_box.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: add

#16 VideoRepositoryImpl getVideoData() 라이브 데이터리스트로 변경
  app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomDatabase.kt
  app/src/main/java/com/example/ymediaapp/data/repository/VideoRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/VideoRepository.kt
Labels: fix

#17 검색 API 레포지토리에 연결
  app/src/main/java/com/example/ymediaapp/data/remote/api/YoutubeService.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/presentation/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/SearchRepository.kt
Labels: update

#18 suspend 추가, Room Entity null 제거
  app/build.gradle.kts
  app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/data/repository/VideoRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/presentation/repository/VideoRepository.kt
  gradle/libs.versions.toml
Labels: fix

#19 Feature/search fragment
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchViewModel.kt
Labels: fix

#21 Service Locator 패턴 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymediaapp/app/AppContainer.kt
  app/src/main/java/com/example/ymediaapp/app/AppFactory.kt
  app/src/main/java/com/example/ymediaapp/app/YMediaApplication.kt
  app/src/main/java/com/example/ymediaapp/app/network/AuthorizationInterceptor.kt
  app/src/main/java/com/example/ymediaapp/app/network/RetrofitClient.kt
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/data/remote/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/data/repository/VideoRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/domain/entity/YoutubeEntity.kt
  app/src/main/java/com/example/ymediaapp/domain/repository/SearchRepository.kt
  app/src/main/java/com/example/ymediaapp/domain/repository/VideoRepository.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeChannelAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeSpinnerAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoRvAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchViewModel.kt
Labels: refactor, fix, move

#23 MyVideo 뷰에 Service Locator 패턴 적용
  app/src/main/java/com/example/ymediaapp/app/AppContainer.kt
  app/src/main/java/com/example/ymediaapp/app/AppFactory.kt
  app/src/main/java/com/example/ymediaapp/app/DummyAuth.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
Labels: update, refactor, move, del

#27 Model, Mapper에서 isLike 제거
  app/src/main/java/com/example/ymediaapp/presentation/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/presentation/model/YoutubeModel.kt
Labels: update

#28 room isLike 제거
  app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
  app/src/main/java/com/example/ymediaapp/data/repository/VideoRepositoryImpl.kt
Labels: fix

#30 코드 클린업, 레이아웃 수정
  app/src/main/java/com/example/ymediaapp/app/AppContainer.kt
  app/src/main/java/com/example/ymediaapp/app/DummyAuth.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoRvAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
  app/src/main/res/layout/fragment_my_video.xml
Labels: fix, move, style

#34 string 리소스 정리, home 리사이클러 뷰 데이터 갱신되면 스크롤 초기화
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/rv_item_home.xml
  app/src/main/res/values/strings.xml
Labels: update

#35 코드 클린업, String 리소스 추출, 앱 아이콘, Repository 메소드 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/ymediaapp/app/AppContainer.kt
  app/src/main/java/com/example/ymediaapp/app/DummyAuth.kt
  app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/ymediaapp/domain/repository/SearchRepository.kt
  app/src/main/res/drawable/play_button.png
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/item_my_video_favorite.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: update, add, fix, style

#37 Feature/search fragment fix
  app/src/main/java/com/example/ymediaapp/app/AppContainer.kt
  app/src/main/java/com/example/ymediaapp/app/network/AuthorizationInterceptor.kt
  app/src/main/java/com/example/ymediaapp/presentation/model/Mapper.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_voice.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: add, fix

#39 Feature/search fragment fix
  app/src/main/java/com/example/ymediaapp/app/network/AuthorizationInterceptor.kt
  app/src/main/java/com/example/ymediaapp/presentation/search/SearchViewModel.kt
Labels: fix

#40 빈 카테고리 버그 수정
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
Labels: bugfix

#41 Temp/detail stt 예외처리, string 리소스 추출
  app/src/main/java/com/example/ymediaapp/presentation/detail/DetailFragment.kt
  app/src/main/java/com/example/ymediaapp/presentation/detail/DetailViewModel.kt
  app/src/main/res/values/strings.xml
Labels: fix
